### ISSUE TITLE
Tar symlinks cannot find layer from external repository

### ISSUE THREAD

**Issue by brett-patterson-ent** [bazel-contrib/rules_oci#566]
I was trying out the `2.x` changes for the performance improvements and ran into an issue where I cannot use a tar file layer from an external repository. The generated `image.sh` will fail to find them:
```
realpath: bazel-out/darwin_arm64-fastbuild/bin/external/_main~_repo_rules~git/data.tar: No such file or directory
```

Sample reproduction: https://github.com/brett-patterson-ent/rules_oci_repro. I have a commented out patch in there that fixes the immediate issue, but I'm not sure if it's the proper fix.

**Comment by gergelytraveltime** [comment]
Probably another repro for the same bug:

https://github.com/bazel-contrib/rules_oci/compare/2.x...gergelyfabian:rules_oci:2.x_symlink_debug

```
bazel build //examples/test2:extended
```

**Comment by gergelyfabian** [comment]
Probably another repro for the same bug:

https://github.com/bazel-contrib/rules_oci/compare/2.x...gergelyfabian:rules_oci:2.x_symlink_debug

```
bazel build //examples/test2:extended
```

**Comment by thesayyn** [comment]
Thank you for making a reproducer, the fix is already here: https://github.com/bazel-contrib/rules_oci/pull/567

**Comment by gergelyfabian** [comment]
Updated my reproduce branch (2.x_symlink_debug) with the latest 2.x branch.
Now there is a different error:

```
$ bazel build //examples/test2:extended
INFO: Invocation ID: e7d1ca03-588c-4e30-bada-640eb623e0b0
INFO: Analyzed target //examples/test2:extended (3 packages loaded, 46 targets configured).
ERROR: /home/user/opt/rules_oci/examples/test2/BUILD:56:10: OCI Image //examples/test2:extended failed: (Exit 1): image_extended.sh failed: error executing OCIImage command (from target //examples/test2:extended) bazel-out/k8-fastbuild/bin/examples/test2/image_extended.sh '--from=bazel-out/k8-fastbuild/bin/examples/test2/base' ... (remaining 5 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ln: Already exists
Target //examples/test2:extended failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.433s, Critical Path: 0.18s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
```

**Comment by thesayyn** [comment]
That makes sense, #576 should fix this for good.

**Comment by gergelyfabian** [comment]
Upgraded my repro branch from this PR, and it still fails:

```
$ bazel build //examples/test2:extended
...
ln: Already exists
```

https://github.com/bazel-contrib/rules_oci/compare/2.x...gergelyfabian:rules_oci:2.x_symlink_debug

**Comment by thesayyn** [comment]
> Upgraded my repro branch from #576, and it still fails:

Thank you. this is fixed by https://github.com/bazel-contrib/rules_oci/pull/576 at 2.x now.
