### ISSUE TITLE
Bad error messaging: zot doesn't understand docker format

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_oci#68]
Trying to build an `oci_image` target fails with

```
ERROR: /home/alexeagle/Projects/a/engineering/projects/hello_world/BUILD.bazel:27:10: OCI Image //a/engineering/projects/hello_world:image failed: (Exit 1): image_image.sh failed: error executing command bazel-out/k8-fastbuild/bin/a/engineering/projects/hello_world/image_image.sh mutate oci:layout/bazel-out/k8-fastbuild/bin/external/distroless_static_debian11_amd64/layout --tag ... (remaining 5 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
2023/02/14 08:43:07 pushed blob: sha256:e5e2a36b2d933eda4e380755c7ed535a46f1a42233234490c40d49c0c326b0fa
2023/02/14 08:43:07 pushed blob: sha256:fc251a6e798157dc3b46fd265da72f39cd848e3f9f4a0b28587d1713b878deb9
Error: PUT http://127.0.0.1:35905/v2/oci/layout/manifests/latest: MANIFEST_INVALID: manifest invalid; [map[mediaType:application/vnd.docker.distribution.manifest.v2+json]]
Error: pulling : parsing reference "": could not parse reference: 
HTTP":{"Address":"127.0.0.1","Port":"0","AllowOrigin":"","TLS":null,"Auth":{"FailDelay":0,"HTPasswd":{"Path":""},"LDAP":null,"Bearer":null},"RawAccessControl":null,"Realm":"","Ratelimit":null},"Log":{"Level":"info","Output":"","Audit":""},"Extensions":null},"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:116","time":"2023-02-14T08:43:07.739974539-08:00","message":"configuration settings"}
```

We should detect the invalid manifest and give the user some idea what this means and how to repair it.

**Comment by thesayyn** [comment]
fixed by #104

**Comment by LavaToaster** [comment]
This error is still surfaced as of the latest commit on main. I didn't know what to do or what it was and have spent a few hours down this hole to realise all I had to do was omit zot attribute from the workspace setup.

**Comment by alexeagle** [comment]
How did you end up with zot in your workspace? Maybe you copied the snippet prior to https://github.com/bazel-contrib/rules_oci/pull/130 ? I added that commit in the hopes of avoiding the few-hours-rabbit-hole.

**Comment by LavaToaster** [comment]
Yeah, we initially set up rules_oci a month or two ago. So it'll predate the changes you made.
